package code;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;

/**
 * this class is used to make a shuffled arraylist of 25 codenames
 * 
 * @author jenny
 */

public class CodenamesList {
	
	/**
	 *  an arraylist that will take in 25 random codenames
	 * to be returned at the end of the method
	 */
	private ArrayList<String> retVal;
	
	/** 
	 * an arraylist that takes in the 400 codenames and shuffles them
	 */
	private ArrayList<String> originalList;
	
	/**
	 * this method takes in an arraylist of 400 words, adds it to a separate array list,
	 * shuffles it, then takes 25 random indexes (courtesy of Google's random number generator)
	 * and adds it to an arraylist to be returned
	 * 
	 * @return a shuffled arraylist of random codenames
	 * @throws FileNotFoundException
	 * @throws IOException
	 */
	public ArrayList<String> getList() throws FileNotFoundException, IOException {
		
		// puts the arraylist from wordsListMaker() into a new one
		originalList = new ArrayList<String>();
		wordsListMaker words = new wordsListMaker();
		originalList = words.getList();
		
		// shuffled new arraylist
		Collections.shuffle(originalList);
		
		retVal = new ArrayList<String>();
		
		// random assignments for the 25 codenames needed (random numbers generated by google)
		retVal.add(originalList.get(165));
		retVal.add(originalList.get(156));
		retVal.add(originalList.get(278));
		retVal.add(originalList.get(377));
		retVal.add(originalList.get(268));
		retVal.add(originalList.get(253));
		retVal.add(originalList.get(10));
		retVal.add(originalList.get(221));
		retVal.add(originalList.get(140));
		retVal.add(originalList.get(192));
		retVal.add(originalList.get(386));
		retVal.add(originalList.get(351));
		retVal.add(originalList.get(363));
		retVal.add(originalList.get(101));
		retVal.add(originalList.get(124));
		retVal.add(originalList.get(176));
		retVal.add(originalList.get(13));
		retVal.add(originalList.get(327));
		retVal.add(originalList.get(383));
		retVal.add(originalList.get(202));
		retVal.add(originalList.get(31));
		retVal.add(originalList.get(341));
		retVal.add(originalList.get(229));
		retVal.add(originalList.get(279));
		retVal.add(originalList.get(103));
		
		return retVal; // returns arraylist with 25 shuffled codenames
		
	}
	
}